CREATE TABLE `case_studies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(500) NOT NULL,
	`titleEn` varchar(500),
	`slug` varchar(500) NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`clientLogo` varchar(500),
	`industry` varchar(100),
	`challenge` text,
	`challengeEn` text,
	`solution` text,
	`solutionEn` text,
	`results` text,
	`resultsEn` text,
	`testimonial` text,
	`testimonialEn` text,
	`testimonialAuthor` varchar(255),
	`testimonialPosition` varchar(255),
	`image` varchar(500),
	`gallery` text,
	`videoUrl` varchar(500),
	`productsUsed` text,
	`metrics` text,
	`sortOrder` int DEFAULT 0,
	`isFeatured` enum('true','false') NOT NULL DEFAULT 'false',
	`isActive` enum('true','false') NOT NULL DEFAULT 'true',
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `case_studies_id` PRIMARY KEY(`id`),
	CONSTRAINT `case_studies_slug_unique` UNIQUE(`slug`)
);
